package com.sparnyuk.quiz;

public class Array {
       final String[][] dictionary ={
               {"certain", "certane", "certain", "наверняка" },
               {"busy", "bisy", "busy", "занят"},
               {"noise", "nurse", "noise", "шум"},
               {"supplies", "suplies", "supplies", "товары"},
               {"desperate", "correa", "desperate", "отчаянный"},
               {"pretend", "fool", "pretend", "притворяться"},
               {"grandson", "abandons", "grandson", "внук"},
               {"groom", "husband", "groom", "жених"},
               {"devoted", "lover", "devoted","любящий"},
               {"thirst", "sett", "thirst","жажда"},

               {"infamy", "infame", "infamy", "позор" },
               {"fool", "bow", "fool", "дурак"},
               {"prevention", "proffilaction", "prevention", "профилактика"},
               {"whip", "wrop", "whip", "кнут"},
               {"tusk", "task", "tusk", "бивень"},
               {"plot", "plat", "plot", "сюжет"},
               {"curse", "cuse", "curse", "проклятие"},
               {"barrel", "barel", "barrel", "бочка"},
               {"beef", "meat", "beef", "говядина"},
               {"railing", "rail", "railing","перила"},

               {"solar", "solaire", "solar", "солнечный" },
               {"bow", "poppy", "bow", "поклониться"},
               {"confident", "wise", "confident", "уверенный"},
               {"shelter", "solter", "shelter", "укрытие"},
               {"antagonist", "indict", "antagonist", "противник"},
               {"conformity", "beyond", "conformity", "соответствие"},
               {"plate", "futon", "plate", "тарелка"},
               {"misery", "afore", "misery", "страдание"},
               {"put", "beyond", "put", "класть"},
               {"frontier", "deeply", "frontier","граница"},

               {"admire", "weak", "admire", "восхищаться" },
               {"unfortunately", "sorry", "unfortunately", "к сожалению"},
               {"from now on", "now", "from now on", "отныне"},
               {"ferris wheel", "faris whole", "ferris wheel", "чертово колесо"},
               {"allowance", "alowence", "allowance", "пособие"},
               {"passionate", "loverly", "passionate", "страстный"},
               {"thought", "think", "thought", "думал"},
               {"count", "plus", "count", "считать"},
               {"make", "take", "make", "делать"},
               {"fall", "down", "fall","падать"},

               {"get", "give", "get", "получать" },
               {"take", "get", "take", "брать"},
               {"thick", "think", "thick", "толстый"},
               {"poverty", "pover", "poverty", "бедность"},
               {"entrance", "exit", "entrance", "вход"},
               {"embarrassing", "mess", "embarrassing", "стеснительный"},
               {"softly", "futon", "softly", "мягко"},
               {"forbidden", "stop", "forbidden", "запрещать"},
               {"patient", "dough", "patient", "терпеливый"},
               {"pretend", "meat", "pretend","притворяться"},

               {"disappear", "proof", "disappear", "исчезнуть" },
               {"courage", "soft", "courage", "храбрость"},
               {"prepared", "ear", "prepared", "приготовиться"},
               {"describe", "bracket", "describe", "описать"},
               {"hop", "hope", "hop", "прыжок"},
               {"proud", "prode", " proud", "гордость"},
               {"responsible", "hop", "responsible", "ответственность"},
               {"reach", "upper", "reach", "дотягиваться"},
               {"hide", "lake", "hide", "прятаться"},
               {"well", "deep", "well","колодец"},

               {"treasure", "solaire", "treasure", "сокровище" },
               {"able", "enable", "able", "способность"},
               {"looking for", "custer", "looking for", "искать"},
               {"loyalty", "lymphy", "loyalty", "преданность"},
               {"necessary", "rashly", "necessary", "необходимость"},
               {"bucket", "larder", "bucket", "ведро"},
               {"rope", "invent", "rope", "веревка"},
               {"stairs", "scrip", "stairs", "лестница"},
               {"sand", "burgle", "sand", "песок"},
               {"suppose", "inlook", "suppose","предполагать"},

               {"swing", "amber", "swing", "качать" },
               {"chores", "her", "chores", "дела по дому"},
               {"fever", "cope", "fever", "жар"},
               {"sour", "luggage", "sour", "кислый"},
               {"scare", "chose", "scare", "пугать"},
               {"borrow", "belief", "borrow", "занимать"},
               {"crumb", "camel", "crumb", "крошка"},
               {"crawl", "altitude", "crawl", "ползать"},
               {"mess", "protect", "mess", "беспорядок"},
               {"couch", "term", "couch","диван"},

               {"upset", "darling", "upset", "расстроенный" },
               {"honest", "fondue", "honest", "честность"},
               {"instead", "radical", "instead", "взамен"},
               {"yell", "beet", "yell", "кричать"},
               {"accidentally", "tyre", " accidentally ", "случайно"},
               {"pour", "outlier", "pour", "поливать"},
               {"huge", "angle", "huge", "огромный"},
               {"raise", "dress", "raise", "повышать"},
               {"pillow", "spooky", "pillow", "подушка"},
               {"throw", "joke", "throw","бросать"},

               {"wing", "paste", "wing", "крыло" },
               {"sailor", "flavour", " sailor ", "моряк"},
               {"matter", "towel", "matter", "значение"},
               {"taste", "prelate", "taste", "вкус"},
               {"exactly", "pity", "exactly", "точно"},
               {"closely", "wide", "closely", "тесно"},
               {"through", "hungry", "through", "сквозь"},
               {"bush", "over", "bush", "куст"},
               {"thorn", "nick", "thorn", "шип"},
               {"reply", " boor", "reply","возразить"}

       }
        ;

}

